spring.datasource.url=jdbc:mariadb://mariadb:3306/${DB_NAME:systema_db}
spring.datasource.username=${DB_USER:docker_user}
spring.datasource.password=${DB_PASS:docker_pass}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.show-sql=false
logging.level.com.tamv.systema=INFO
